#ifndef DSTSRCONFIG_GLOBAL_H
#define DSTSRCONFIG_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DSTSRCONFIG_LIBRARY)
#  define DSTSRCONFIGSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DSTSRCONFIGSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DSTSRCONFIG_GLOBAL_H
