#ifndef PLCSRCONFIG_GLOBAL_H
#define PLCSRCONFIG_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PLCSRCONFIG_LIBRARY)
#  define PLCSRCONFIGSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PLCSRCONFIGSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PLCSRCONFIG_GLOBAL_H
